"""create initial schema

Revision ID: f9b7e11ddb73
Revises: 
Create Date: 2026-09-03 04:58:51.692223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b7e11ddb73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_locations_id'), 'delivery_locations', ['id'], unique=False)
    op.create_table('demand_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observed_date', sa.Date(), nullable=False),
    sa.Column('product', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('buyer_type', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_observations_buyer_type'), 'demand_observations', ['buyer_type'], unique=False)
    op.create_index(op.f('ix_demand_observations_id'), 'demand_observations', ['id'], unique=False)
    op.create_index(op.f('ix_demand_observations_location'), 'demand_observations', ['location'], unique=False)
    op.create_index(op.f('ix_demand_observations_observed_date'), 'demand_observations', ['observed_date'], unique=False)
    op.create_index(op.f('ix_demand_observations_product'), 'demand_observations', ['product'], unique=False)
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('training_rows', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(length=30), nullable=False),
    sa.Column('mae', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('rmse', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('mape', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('baseline_mae', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_runs_id'), 'forecast_runs', ['id'], unique=False)
    op.create_table('pickup_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickup_locations_id'), 'pickup_locations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('fpos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_fpos_id'), 'fpos', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_address', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_buyer_id'), 'orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_seller_id'), 'orders', ['seller_id'], unique=False)
    op.create_table('purchase_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('required_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quality', sa.String(length=30), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_location', sa.String(length=500), nullable=False),
    sa.Column('delivery_deadline', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('matched_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_requirements_buyer_id'), 'purchase_requirements', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_purchase_requirements_id'), 'purchase_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_requirements_product_name'), 'purchase_requirements', ['product_name'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=40), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_operator_id'), 'vehicles', ['operator_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('logistics_operator_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_location', sa.String(length=150), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('pickup_location_id', sa.Integer(), nullable=True),
    sa.Column('delivery_location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_location_id'], ['delivery_locations.id'], ),
    sa.ForeignKeyConstraint(['logistics_operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['pickup_locations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_deliveries_id'), 'deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_deliveries_logistics_operator_id'), 'deliveries', ['logistics_operator_id'], unique=False)
    op.create_table('fpo_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fpo_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fpo_id'], ['fpos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fpo_members_farmer_id'), 'fpo_members', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_fpo_members_fpo_id'), 'fpo_members', ['fpo_id'], unique=False)
    op.create_index(op.f('ix_fpo_members_id'), 'fpo_members', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('fpo_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('quality', sa.String(length=30), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_aggregated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fpo_id'], ['fpos.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_fpo_id'), 'products', ['fpo_id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_seller_id'), 'products', ['seller_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('waypoint_order', sa.JSON(), nullable=False),
    sa.Column('baseline_waypoint_order', sa.JSON(), nullable=False),
    sa.Column('total_distance_km', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estimated_travel_time_min', sa.Integer(), nullable=False),
    sa.Column('number_of_stops', sa.Integer(), nullable=False),
    sa.Column('capacity_utilization_percent', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('baseline_distance_km', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('routing_provider', sa.String(length=80), nullable=False),
    sa.Column('is_demo_environment', sa.Boolean(), nullable=False),
    sa.Column('optimized_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_buyer_id'), 'cart_items', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.create_table('fpo_inventory_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fpo_id', sa.Integer(), nullable=False),
    sa.Column('aggregated_product_id', sa.Integer(), nullable=False),
    sa.Column('source_product_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('consumed_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['aggregated_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fpo_id'], ['fpos.id'], ),
    sa.ForeignKeyConstraint(['source_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fpo_inventory_allocations_aggregated_product_id'), 'fpo_inventory_allocations', ['aggregated_product_id'], unique=False)
    op.create_index(op.f('ix_fpo_inventory_allocations_farmer_id'), 'fpo_inventory_allocations', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_fpo_inventory_allocations_fpo_id'), 'fpo_inventory_allocations', ['fpo_id'], unique=False)
    op.create_index(op.f('ix_fpo_inventory_allocations_id'), 'fpo_inventory_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_fpo_inventory_allocations_source_product_id'), 'fpo_inventory_allocations', ['source_product_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('requirement_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('matched_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['purchase_requirements.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_matches_id'), 'requirement_matches', ['id'], unique=False)
    op.create_index(op.f('ix_requirement_matches_product_id'), 'requirement_matches', ['product_id'], unique=False)
    op.create_index(op.f('ix_requirement_matches_requirement_id'), 'requirement_matches', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_requirement_matches_supplier_id'), 'requirement_matches', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirement_matches_supplier_id'), table_name='requirement_matches')
    op.drop_index(op.f('ix_requirement_matches_requirement_id'), table_name='requirement_matches')
    op.drop_index(op.f('ix_requirement_matches_product_id'), table_name='requirement_matches')
    op.drop_index(op.f('ix_requirement_matches_id'), table_name='requirement_matches')
    op.drop_table('requirement_matches')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_fpo_inventory_allocations_source_product_id'), table_name='fpo_inventory_allocations')
    op.drop_index(op.f('ix_fpo_inventory_allocations_id'), table_name='fpo_inventory_allocations')
    op.drop_index(op.f('ix_fpo_inventory_allocations_fpo_id'), table_name='fpo_inventory_allocations')
    op.drop_index(op.f('ix_fpo_inventory_allocations_farmer_id'), table_name='fpo_inventory_allocations')
    op.drop_index(op.f('ix_fpo_inventory_allocations_aggregated_product_id'), table_name='fpo_inventory_allocations')
    op.drop_table('fpo_inventory_allocations')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_buyer_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_products_seller_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_fpo_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_fpo_members_id'), table_name='fpo_members')
    op.drop_index(op.f('ix_fpo_members_fpo_id'), table_name='fpo_members')
    op.drop_index(op.f('ix_fpo_members_farmer_id'), table_name='fpo_members')
    op.drop_table('fpo_members')
    op.drop_index(op.f('ix_deliveries_logistics_operator_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_vehicles_operator_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_purchase_requirements_product_name'), table_name='purchase_requirements')
    op.drop_index(op.f('ix_purchase_requirements_id'), table_name='purchase_requirements')
    op.drop_index(op.f('ix_purchase_requirements_buyer_id'), table_name='purchase_requirements')
    op.drop_table('purchase_requirements')
    op.drop_index(op.f('ix_orders_seller_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_fpos_id'), table_name='fpos')
    op.drop_table('fpos')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pickup_locations_id'), table_name='pickup_locations')
    op.drop_table('pickup_locations')
    op.drop_index(op.f('ix_forecast_runs_id'), table_name='forecast_runs')
    op.drop_table('forecast_runs')
    op.drop_index(op.f('ix_demand_observations_product'), table_name='demand_observations')
    op.drop_index(op.f('ix_demand_observations_observed_date'), table_name='demand_observations')
    op.drop_index(op.f('ix_demand_observations_location'), table_name='demand_observations')
    op.drop_index(op.f('ix_demand_observations_id'), table_name='demand_observations')
    op.drop_index(op.f('ix_demand_observations_buyer_type'), table_name='demand_observations')
    op.drop_table('demand_observations')
    op.drop_index(op.f('ix_delivery_locations_id'), table_name='delivery_locations')
    op.drop_table('delivery_locations')
    # ### end Alembic commands ###
